app/views/spree/admin/orders/_stock_item.html.erb, config/locales/en.yml
This translation was new to Solidus 1.3, I think it's easiest to just
backfill here to prevent Spree.t from inserting a span which breaks html
when used inside of a tag attribute
eg: title="<span class="translation_missing
=> Add missing translation for actions.delete

app/views/spree/admin/parts/index.html.erb
`solidus_version` is a class method not an instance method, this was showing the sub_menu on *all* versions of Solidus, not just the oldest ones as intended.
=> Fix product sub_menu display on new Solidus

app/models/spree/stock/inventory_validator_decorator.rb
On cached environments, when redefining the class, the original method
is what is defined. We're not entirely sure why, but this should be
class eval'd anyway instead of redefining the class.
=> Fix a load order issue when redefining inventory validator.

app/controllers/spree/admin/parts_controller.rb, app/models/spree/line_item_decorator.rb, app/views/spree/admin/orders/_stock_item.html.erb, app/views/spree/checkout/_line_item_manifest.html.erb
This fixes an error on Solidus >= 2.1, where we've removed `mini_image`
=> Fix deprecations and removals

README.md
The README contained old information pertaining to old versions of Spree. For instance, it referred to a `2-0-stable` branch which does not exist in the current repository. It also included references to a migration from Spree 2.0 and earlier, but the Solidus fork begins at Spree 2.4, so I believe this is no longer necessary.
=> Remove old Spree information from README

app/models/spree/stock/inventory_unit_builder_decorator.rb, spec/models/spree/inventory_unit_spec.rb, spec/models/spree/shipment_spec.rb, spec/models/spree/stock/inventory_unit_builder_spec.rb
Solidus 2.5 removes the order association from inventory units, so we
need to check what version we're on and act accordingly.
=> Update for Solidus 2.5

app/decorators/models/spree/stock/availability_validator_decorator.rb, spec/models/spree/stock/availability_validator_spec.rb
When validating line items for products that are not assemblies, we should delegate to the original Solidus implementation.
=>  AvailabilityValidator delegates to Solidus implementation when product is not an assembly

app/overrides/spree/admin/orders/_shipment/stock_contents.html.erb.deface, app/views/spree/admin/orders/_stock_contents.html.erb, app/views/spree/admin/orders/_stock_contents_2_3.html.erb, app/views/spree/admin/orders/_stock_contents_2_4.html.erb, spec/features/admin/orders_spec.rb
Shipping costs and tracking areas in the admin order page were no more
synchronized with current Solidus behavior.
The code that is being removed in this commit, after some changes, was removed
from Solidus with commit 5497ee.
A few regression tests are added.
Together with functionality, also the layout was broken, see attached screenshot
=> Fix admin edit for shipping costs and tracking

app/views/spree/api/line_items/show.v1.rabl
Line items don't provide informations about parts through API views.
Add parts informations. Now the result json is:
line_item:
variant:
variant attributes...
parts:
0:
variant attributes...
1:
variant attributes...
=> Parts informations in API

app/views/spree/admin/orders/_stock_item.html.erb
REF #23 
The `edit` button is not working anymore. After some investigation it comes
out that the button was removed from Solidus back in 2014 with commit
`b252e9adcd02b5b0f0f89cdcfae583e72ae12fb7`.
Allo other issues with #23 have been fixed with recent commits.
=> Remove stale edit button

solidus_product_assembly.gemspec
SQLite3 v1.4 was released on February 4th, which breaks compatibility with ActiveRecord's adapter for said DB engine.
=> Lock SQLite3 to version 1.3

app/overrides/spree/products/show/add_links_to_parts.html.erb.deface, app/views/spree/admin/orders/_stock_contents_2_4.html.erb
`Spree.t` has been deprecated in favor of `I18n.t`
=> Replace `Spree.t` with `I18n.t`

app/models/spree/calculator/returns/assemblies_default_refund_amount.rb, app/models/spree/return_item_decorator.rb, spec/features/admin/return_items_spec.rb
When the product is an assembly composed of multiple parts, the proposed refund
amount for each part is now calculated proportionally by using the custom class
`Spree::Calculator::Returns::AssembliesDefaultRefundAmount`.
=> Split refund amount proportionally on each assembly part

app/decorators/models/spree/stock/inventory_units_finalizer_decorator.rb, spec/features/checkout_spec.rb
This gem seems to be working fine as long as products stock is backorderable,
but Solidus 2.8 with `Spree::Stock::InventoryUnitsFinalizer` changed how
inventory units are unstocked.
A new set of specs verifies what happens during the checkout process when the
stock is not backorderable.
=> Fix stock finalization with non-backorderable stock and Solidus >= 2.8

app/overrides/spree/admin/orders/_carton_manifest/_assembly_parts_price.html.erb.deface, app/overrides/spree/admin/orders/_carton_manifest/_assembly_parts_total_price.html.erb.deface, spec/features/checkout_spec.rb
When listing assembly parts, it does not make sense to show the assembly price
(total price) for each part. A few dashes `---` will be shown instead, as already
happens in other parts of the admin when assemblies are involved.
Also, in order to avoid regressions a new feature spec that tests much of the 
admin order processing with product assemblies is added.
=> Remove assembly part prices from carton manifest

app/models/spree/calculator/returns/assemblies_default_refund_amount.rb, spec/features/admin/return_items_spec.rb
Solidus rounds down refund amounts, so in order to ensure the whole order is properly refunded when all assembly parts are returned some minimal rounding up is required, or there will very likely be one cent difference between the payment amount and the refund amount:
See Solidus core method `Spree::Reimbursement#calculated_total` comments:
```ruby
def calculated_total
return_items.to_a.sum(&:total).to_d.round(2, :down)
end
```
The existing integration spec was expanded in order to verify the whole refund process, starting from the RMA, then generating a return and finally the complete refund.
=> Round up default refund amount for assembly parts

.travis.yml, solidus_product_assembly.gemspec
The current version of Chrome is not compatible anymore with Capybara 2.X, so
the gem version must be upgraded. In order to use the most recent version,
Ruby version must be upgraded too. The new Ruby version is the same of Solidus.
=> Fix build on Travis

app/models/spree/calculator/returns/assemblies_default_refund_amount.rb, spec/features/admin/return_items_spec.rb
Ref #46
When returning an order with assembly product line items with quantity > 1,
the suggested return amount calculator should consider also the quantity.
This is already done for regular products within Solidus codebase, so the
algorythm in `AssembliesDefaultRefundAmount#compute` must only consider
assembly product return items.
=> Fix return item amounts with multiple items

app/views/spree/admin/orders/_stock_item.html.erb
I think there's actually no reason to forbid shipment splitting for assembled items.
=> Show split/delete actions for all items (admin/orders/shipment)

app/views/spree/admin/orders/_stock_item.html.erb
This brings _stock_item.html.erb more in line with Solidus' _shipment_manifest.html.erb by
adding the link to edit the variant and displaying the SKU when available.
https://github.com/solidusio/solidus/blob/master/backend/app/views/spree/admin/orders/_shipment_manifest.html.erb
=> Add SKU to _stock_item

app/views/spree/admin/orders/_assemblies.html.erb, app/views/spree/admin/orders/_stock_contents_2_3.html.erb, app/views/spree/admin/orders/_stock_contents_2_4.html.erb, app/views/spree/admin/orders/_stock_item.html.erb, app/views/spree/admin/parts/_parts_table.html.erb, app/views/spree/admin/parts/available.html.erb, app/views/spree/admin/parts/available.js.erb, app/views/spree/admin/parts/index.html.erb, app/views/spree/admin/products/_product_assembly_fields.html.erb, app/views/spree/admin/shared/_product_assembly_product_tabs.html.erb
Vanilla `I18n.t` should not be used in views; the wrapped version from `ActionView::Helpers::TranslationHelper.t` should be unsed instead.
See https://api.rubyonrails.org/v5.2.2/classes/ActionView/Helpers/TranslationHelper.html
=> Use `ActionView::Helpers::TranslationHelper.t`

spec/features/admin/return_items_spec.rb
In the current version of Solidus it is required to pass an user to this method.
=> Remove deprecation for Reimbursement#simulate

app/views/spree/admin/orders/_assemblies.html.erb, spec/features/admin/orders_spec.rb
Ref #62 
These buttons are probably legacy code. I run the test suite
with older Solidus versions (v2.5, v2.4, v2.3) and still they
did not work. A spec existed for this feature, but it did not
verify that it actually works.
This functionality, however, exists (in working conditions and
is implemented in Solidus backend codebase) in the admin `Cart`
page, so I think it makes sense removing it altogether from the
`Shipments` page.
=> Remove broken buttons in Shipments page

app/decorators/models/solidus_product_assembly/spree/stock/inventory_unit_builder_decorator.rb
I've got a lot of these warnings in my logs : 
```
DEPRECATION WARNING: SolidusSupport.solidus_gem_version is deprecated and will be removed in solidus_support 1.0. Please use Spree.solidus_gem_version instead. (called from build_inventory_unit at /home/circleci/epicery/api/vendor/bundle/bundler/gems/solidus_product_assembly-c52438ea289e/app/models/spree/stock/inventory_unit_builder_decorator.rb:18)
```
This change should get rid of them :)
=> Fix deprecation warning about SolidusSupport.solidus_gem_version

app/models/spree/order_inventory_assembly.rb
This PR becomes necessary after https://github.com/solidusio/solidus/pull/3197 is merged in Solidus master. 
ATM the Solidus version in this branch points to the version included in https://github.com/solidusio/solidus/pull/3197 in order to ensure functionality.
The arity of the method `OrderInventory#determine_target_shipment` changes with
Solidus PR #3197, this change must be ported to `OrderInventoryAssembly#verify`
=> Update `#determine_target_shipment` after Solidus #3197

spec/features/checkout_spec.rb
Because of addresses' firstname & lastname deprecations in solidusio/solidus#3584, solidusio/solidus#3524 and probably other PRs, the inputs where deleted in favor of a single `name` input.
This is only on master for now, so it should be in 2.11 or 3.0.
=> Fix failing spec since Solidus address format change

README.md
The Readme points to Spree's guidelines, and the url is now broken anyway.
Let's link to the relevant [page](https://solidus.io/community-guidelines/) on Solidus' website instead. 🙂
=> Fix Community Guidelines link in Readme

app/views/spree/admin/parts/_parts_table.html.erb, app/views/spree/admin/parts/available.html.erb, app/views/spree/admin/parts/available.js.erb
At @epicery, account managers (who handle product catalogs) felt the need to know whether products are available when creating a bundle of products.
Rather than monkey patching the extension, we thought this small change might be of interest for the community.
More precisely, this PR simply adds another column to the `<table>` elements defined in both the `admin/parts/_parts_table` partial and the `admin/parts/available` view, as illustrated by the following gif:
=> Display parts' available_on in the admin's "parts" tab (feature proposal)

spec/models/spree/shipment_spec.rb
We need a store to satisfy the presence validation on `:store_id` as defined in solidus_core's `Spree::Order` model.
=> Fix failing test in shipment_spec due to missing store

app/decorators/models/solidus_product_assembly/spree/inventory_unit_decorator.rb, lib/solidus_product_assembly/engine.rb, solidus_product_assembly.gemspec
This PR is a proposal to follow the same relaxed version requirement for `solidus_support` as implemented by most other extensions.
This brings the benefit of not having to define `::activate` in _engine.rb_ to load decorators anymore.
=> Bump solidus_support dependency to (~> 0.5)

app/overrides/add_admin_product_form_fields.rb, app/overrides/add_admin_tabs.rb, app/overrides/add_line_item_description.rb, app/overrides/spree/admin/products/_form/product_assembly_product_form_right.deface, app/overrides/spree/admin/shared/_product_tabs/product_assembly_admin_product_tabs.deface, app/overrides/spree/orders/_line_item/product_assembly_cart_item_description.deface, lib/solidus_product_assembly/version.rb
This PR replaces the use of the Deface Ruby overrides with the Deface DSL. This makes this gem compatible with Rails 7.1, since the Deface overrides tend to break Zeitwerk naming conventions.
=> Replace Deface Ruby with DSL
